export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({ children }) {
  // In app router, only the root layout should render <html>/<body>.
  // This nested layout just composes the section.
  return <>{children}</>;
}
